Increment 5
e1m0re/grdn pull request #5
Opened 2024-03-11 18:41 UTC by e1m0re

2024-03-12 13:29 UTC, arttet requested changes
Please add
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-12 13:29 UTC, arttet commented on cmd/agent/flags.go
> +var agentOptions = new(Options)
```suggestion
var agentOptions = &Options{}
```

2024-03-12 13:29 UTC, arttet commented on cmd/agent/flags.go
> +var agentOptions = new(Options)
CHANGE REQUEST: please avoid global variables

2024-03-12 13:29 UTC, arttet commented on cmd/agent/flags.go
> +	var defaultA = "localhost:8080"
CHANGE REQUEST: this is a magic name

2024-03-12 13:29 UTC, arttet commented on cmd/agent/flags.go
> +	var defaultR = uint(10)
```suggestion
	defaultR := uint(10)
```

2024-03-12 13:29 UTC, arttet commented on cmd/agent/main.go
> +func UpdateMetrics(data *storage.MetricsState) {
CHANGE REQUEST: please split your application by layers. Here is business logic.

2024-03-12 13:29 UTC, arttet commented on cmd/server/main.go
> +func updateMetricHandler(response http.ResponseWriter, request *http.Request) {
CHANGE REQUEST: it should be a method

2024-03-13 15:45 UTC, e1m0re commented on cmd/agent/flags.go
> +var agentOptions = new(Options)
done

2024-03-13 15:45 UTC, e1m0re commented on cmd/agent/flags.go
> +var agentOptions = new(Options)
ok

2024-03-13 15:46 UTC, e1m0re commented on cmd/agent/flags.go
> +	var defaultA = "localhost:8080"
renamed

2024-03-13 15:46 UTC, e1m0re commented on cmd/agent/flags.go
> +	var defaultR = uint(10)
fixit

2024-03-13 15:47 UTC, e1m0re commented on cmd/agent/main.go
> +func UpdateMetrics(data *storage.MetricsState) {
done

2024-03-13 15:52 UTC, e1m0re commented on cmd/server/main.go
> +func updateMetricHandler(response http.ResponseWriter, request *http.Request) {
I've moved Business logic to store.

2024-03-13 16:47 UTC, arttet requested changes

2024-03-13 16:47 UTC, arttet commented on cmd/server/main.go
> +var store = storage.NewMemStorage()
CHANGE REQUEST: please don't use global variables

2024-03-13 16:47 UTC, arttet commented on cmd/server/main.go
> +func updateMetricHandler(response http.ResponseWriter, request *http.Request) {
```suggestion
func (h *Handler) updateMetricHandler(response http.ResponseWriter, request *http.Request) {
```

2024-03-13 19:40 UTC, e1m0re commented on cmd/server/main.go
> +var store = storage.NewMemStorage()
fixit

2024-03-13 19:40 UTC, e1m0re commented on cmd/server/main.go
> +func updateMetricHandler(response http.ResponseWriter, request *http.Request) {
done

2024-03-13 19:44 UTC, e1m0re commented on cmd/server/main.go
> +func updateMetricHandler(response http.ResponseWriter, request *http.Request) {
Now I understand what you meant and I fixed it.

2024-03-13 19:46 UTC, e1m0re commented
done

2024-03-15 16:33 UTC, arttet requested changes

2024-03-15 16:33 UTC, arttet commented on .github/workflows/coveragetest.yml
> +        uses: codecov/codecov-action@v3
```suggestion
        uses: codecov/codecov-action@v4
```

2024-03-15 16:33 UTC, arttet commented on .github/workflows/coveragetest.yml
> +          go-version: '1.21'
```suggestion
          go-version: '1.22'
```

2024-03-15 16:33 UTC, arttet commented on Makefile
> +	go run cmd/agent/main.go cmd/agent/flags.go
```suggestion
	go run cmd/agent/main.go
```

2024-03-15 16:33 UTC, arttet commented on cmd/agent/flags.go
> +var agentOptions = &Options{}
CHANGE REQUEST: please avoid global variables

2024-03-15 16:33 UTC, arttet commented on internal/srvhandler/srvhandler.go
> +func (h *Handler) UpdateMetric(store *storage.MemStorage) http.HandlerFunc {
```suggestion
func (h *Handler) UpdateMetric(response http.ResponseWriter, request *http.Request) {
```

2024-03-15 16:35 UTC, arttet commented
[2024-03-14T06:49:31.691Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}

2024-03-18 14:20 UTC, arttet approved these changes

2024-03-18 14:20 UTC, arttet commented on cmd/agent/main.go
> +	flag.StringVar(&flagRunAddr, "a", "localhost:8080", "address and port to run server")
SUGGESTION: it should be in `flags.go`

2024-03-18 15:00 UTC, merged